### ISSUE TITLE
Improve the install instructions

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds-www#59]
The current installation instructions are potentially confusing, more so for the users who need the help most (typically Windows ones).

We have a lot of ways to install RGBDS; in no particular order:

- Homebrew on macOS
- Pacman on Arch Linux
- Docker (if you have that installed)
- Building from source...
  - ...using a downloaded .zip or Git clone
  - ...getting prerequisites with your Linux/WSL package manager, macOS `brew`, or (most complicated) Cygwin
  - ...using `make` or `cmake`
    - ...plus more variants for old `cmake` versions
  - ...and how to add it to `PATH` for Windows
    - ...with `cmd` or Powershell
- Using `rgbenv` (which has its own build instructions)
- Another page on how to use the `master` development branch...
  - ...building from source (semi-redundant)
  - ...Pacman on Arch Linux
  - ...the CI builds (are these even worth officially promoting? especially given that "We only recommend doing this on Windows", but IMO shouldn't recommend something for Windows users that takes them to a page like [this](https://github.com/gbdev/rgbds/actions?query=workflow%3A%22Regression+testing%22))

I think we should prioritize using the releases published on GitHub (with a separate page for Windows users explaining how to add the new .exe files to their `PATH`).

Secondly, mention the packaged options for macOS and Arch Linux.

Thirdly, a separate page on how to build from source. This would have sections on how to install the prerequisites (with `apt`, `pacman`, `brew`, Cygwin, etc), get the source (download the .zip or `git clone`), build (`make` or `cmake`), and install (`make install` or adding to `PATH`).

**Comment by rondnelson99** [comment]
A couple days I built RGBDS for the first time in around six months, so my perspective might be relevant. I use WSL.

Having done this before, I knew I just needed to get the right dependencies, clone and make, but I didn't remember what the dependencies were.

First, I went to the README on GitHub since that's where that information usually is on larger projects. I wasn't really reading fully, so I just clicked the "installation procedure" like before seeing the "build from source" link. 

Once I was at https://rgbds.gbdev.io/install/, I looked through all the big headings, but none of them were for building. Eventually I found the build from source link near the top of the page, but I feel like building from source is a common enough way to install RGBDS that it should warrant its own big heading, even if that still just has a link to another page like it does.

The other issue is that the "build from source" link on the GitHub readme is broken right now, sending to the general install page instead. I could PR that fix.

**Comment by LIJI32** [comment]
The website is missing direct download links to the official binary builds of RGBDS for both macOS and Windows. (On the Windows side there's at least some "guide" on where to find these (rather than just a link), but macOS has nothing). The download links should be much more accessible from the main website.
